- name: write inventory to file
    env:
      INVENTORY: ${{ secrets.INVENTORY }}
    run: 'echo "$INVENTORY" > inventory'
    
    - name: run playbook
    run: |
      ansible-playbook -i inventory ansible/hello-world.yaml
